[features]
seeds = false
[programs.localnet]
programs = "JAGvz6e56Rmh66rqe4BHgjhA5VtYYGZSBN8HTu1zRQ88"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
